### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by podborski**
***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Oct 10, 2022, 9:54 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.

:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FAOMediaCodec%2Fav1-hdr10plus%2Fdea1abf401928ba7500667300c556d4730fbddea%2Findex.bs&md-warning=not%20ready)

```
Error running preprocessor, returned code: 1.
Traceback (most recent call last):
  File "/sites/api.csswg.org/python310venv/bin/bikeshed", line 8, in 
    sys.exit(main())
  File "/sites/api.csswg.org/python310venv/lib/python3.10/site-packages/bikeshed/cli.py", line 423, in main
    handleSpec(options, extras)
  File "/sites/api.csswg.org/python310venv/lib/python3.10/site-packages/bikeshed/cli.py", line 478, in handleSpec
    doc.preprocess()
  File "/sites/api.csswg.org/python310venv/lib/python3.10/site-packages/bikeshed/Spec.py", line 145, in preprocess
    self.processDocument()
  File "/sites/api.csswg.org/python310venv/lib/python3.10/site-packages/bikeshed/Spec.py", line 264, in processDocument
    boilerplate.addIndexSection(self)
  File "/sites/api.csswg.org/python310venv/lib/python3.10/site-packages/bikeshed/boilerplate.py", line 304, in addIndexSection
    addIndexOfExternallyDefinedTerms(doc, container)
  File "/sites/api.csswg.org/python310venv/lib/python3.10/site-packages/bikeshed/boilerplate.py", line 570, in addIndexOfExternallyDefinedTerms
    dfnpanels.addExternalDfnPanel(link, ref, doc)
  File "/sites/api.csswg.org/python310venv/lib/python3.10/site-packages/bikeshed/dfnpanels.py", line 99, in addExternalDfnPanel
    for link in doc.cachedLinksFromHref[ref.url]:
KeyError: '#biblio-av1'
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20AOMediaCodec/av1-hdr10plus%2344.)._
</details>

### CODE REVIEW

**Comment by cconcolato** [comment]
As discussed in the meeting, the comments on this PR are:
1. in the introduction, revert the sentence merge, keep HDR10+, remove "which"
2. replace "shall be set" to "is" (2x) and "shall be interpreted" becomes "is interpreted", "shall be set" becomes "are set"
3. remove "that remain constant for the entire sequence"
4. move show existing frame = 1 into the pink frame
5. revert figure 2 title and use the same in the corresponding sentence
6 In 3.2 revert "that"/"to"

**Comment by podborski** [comment]
> As discussed in the meeting, the comments on this PR are:
> 
> 1. in the introduction, revert the sentence merge, keep HDR10+, remove "which"
> 2. replace "shall be set" to "is" (2x) and "shall be interpreted" becomes "is interpreted", "shall be set" becomes "are set"
> 3. remove "that remain constant for the entire sequence"
> 4. move show existing frame = 1 into the pink frame
> 5. revert figure 2 title and use the same in the corresponding sentence
>    6 In 3.2 revert "that"/"to"

@cconcolato please check if I addressed all the comments correctly.

**Comment by cconcolato** [comment]
@podborski It looks good to me. The last change could have used "be" instead of "are" as in the current version but I don't think it's wrong.

**Review by cconcolato — APPROVED** [review]

**Comment by cconcolato** [comment]
Let me know if you want me to merge.

**Comment by podborski** [comment]
@cconcolato one more change. I moved `CICP` from informative to normative references. This is because the values are normatively specified in the text.

If everyone is ok, we can merge.

**Comment by cconcolato** [comment]
It's all good to me. I'm merging for the board review to happen

**Pull request merged**
